package leetcode.strings;

/**
 * You are given two strings s and t. String t is generated by random shuffling string s
 * and then add one more letter at a random position. Return the letter that was added to t.
 */
public class FindDifferenceInChar {
    public static void main(String args[])
    {
        System.out.println(findTheDifference("aaaa", "aaaba"));
    }
    public static char findTheDifference(String s, String t) {
        int sumS = 0, sumT = 0;
        char ch;

        for (int i = 0; i <s.length(); i++) {
            System.out.println("on string S; char at " + i + " is " + s.charAt(i));
            sumS += s.charAt(i);
            System.out.println("sumS " + sumS);
        }

        for (int j = 0; j < t.length(); j++) {
            System.out.println("on string T; char at " + j + " is " + t.charAt(j));
            sumT += Integer.valueOf(t.charAt(j));
        }


        ch = (char) (sumT - sumS);
        return ch;
    }
}
